<?php

namespace ContainerQ0Tw21C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\VideoFormType' shared autowired service.
     *
     * @return \App\Form\VideoFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/VideoFormType.php';

        return $container->privates['App\\Form\\VideoFormType'] = new \App\Form\VideoFormType();
    }
}
