liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: ~ # %kernel.project_dir%/public (%kernel.project_dir%/web for Symfony < 4.0.0)
                cache_prefix: ~ # media/cache

    filter_sets:
        profile_picture:
            quality: 50
            filters:
                thumbnail: { size: [70, 70], mode: outbound }