<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ0Tw21C\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ0Tw21C/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ0Tw21C.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ0Tw21C\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ0Tw21C\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q0Tw21C',
    'container.build_id' => 'f97ce6ba',
    'container.build_time' => 1636303467,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ0Tw21C');
