<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFUxLuwG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFUxLuwG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFUxLuwG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFUxLuwG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFUxLuwG\App_KernelDevDebugContainer([
    'container.build_hash' => 'FUxLuwG',
    'container.build_id' => 'dc62d6da',
    'container.build_time' => 1638641941,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFUxLuwG');
